services:
  db:
    image: postgres:16-alpine
    container_name: category-tree-db
    env_file: [.env]
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
    name: category-tree-db-volume