"""empty message

Revision ID: 4fe32c8aa969
Revises: db3cce311c4e
Create Date: 2025-09-10 14:12:27.378352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe32c8aa969'
down_revision: Union[str, Sequence[str], None] = 'db3cce311c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_product_in_order', 'order_item', ['product_id', 'order_id'])
    op.create_unique_constraint('unique_product_category', 'product_category', ['product_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_product_category', 'product_category', type_='unique')
    op.drop_constraint('unique_product_in_order', 'order_item', type_='unique')
    # ### end Alembic commands ###
