"""empty message

Revision ID: db3cce311c4e
Revises: b0dcc369aaa6
Create Date: 2025-09-09 17:00:51.424303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db3cce311c4e'
down_revision: Union[str, Sequence[str], None] = 'b0dcc369aaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk__product_category__category_id__category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk__product_category__product_id__product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', 'id', name=op.f('pk__product_category')),
    sa.UniqueConstraint('id', name=op.f('uq__product_category__id'))
    )
    op.create_index(op.f('ix__product_category__category_id'), 'product_category', ['category_id'], unique=False)
    op.create_index(op.f('ix__product_category__product_id'), 'product_category', ['product_id'], unique=False)
    op.create_unique_constraint(op.f('uq__category__id'), 'category', ['id'])
    op.create_unique_constraint(op.f('uq__client__id'), 'client', ['id'])
    op.create_unique_constraint(op.f('uq__order__id'), 'order', ['id'])
    op.create_unique_constraint(op.f('uq__order_item__id'), 'order_item', ['id'])
    op.create_unique_constraint(op.f('uq__product__id'), 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__product__id'), 'product', type_='unique')
    op.drop_constraint(op.f('uq__order_item__id'), 'order_item', type_='unique')
    op.drop_constraint(op.f('uq__order__id'), 'order', type_='unique')
    op.drop_constraint(op.f('uq__client__id'), 'client', type_='unique')
    op.drop_constraint(op.f('uq__category__id'), 'category', type_='unique')
    op.drop_index(op.f('ix__product_category__product_id'), table_name='product_category')
    op.drop_index(op.f('ix__product_category__category_id'), table_name='product_category')
    op.drop_table('product_category')
    # ### end Alembic commands ###
